### PR TITLE
update Dockerfile.nvcc to use HDF5 version 1.10.7

### PR DESCRIPTION
**Pull request by jlippuner**
## PR Summary

Update `Dockerfile.nvcc` for gitlab CI to use HDF5 version 1.10.7.

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by JoshuaSBrown — APPROVED** [review]

**Review by JoshuaSBrown — CHANGES_REQUESTED** [review]
Can you add this dependency version requirement to CMake? Seems like it might be appropriate.

**Comment by pgrete** [comment]
> Can you add this dependency version requirement to CMake? Seems like it might be appropriate.

I think this will first become relevant in the other PR where compression can be used.
Also that requirement should then depend on whether compression support is built in or not.

**Comment by jlippuner** [comment]
> Can you add this dependency version requirement to CMake? Seems like it might be appropriate.

A version check is added to CMake in PR #486 where we really need the newer version of HDF5.

**Comment by jlippuner** [comment]
> > Can you add this dependency version requirement to CMake? Seems like it might be appropriate.
> 
> I think this will first become relevant in the other PR where compression can be used.
> Also that requirement should then depend on whether compression support is built in or not.

Yup, the HDF5 version will only be checked if compression and parallel I/O is enabled, because that's what triggers the bug in older HDF5 versions.

**Review by JoshuaSBrown — APPROVED** [review]

**Review by pgrete — APPROVED** [review]

**Pull request merged**
