### PR TITLE
Fix hanging compilation for sort unit test

### PR DESCRIPTION
**Pull request by brryan**
## PR Summary

Compilation of `test_unit_sort.cpp` hangs on some platforms (see #672). Switching the value in the key-value pair for this test from `char[STRLEN]` to `int` resolves this issue for me on the power9 archiecture when compiling with CUDA. The test still tests the same behavior.

## PR Checklist

- [x] Code passes cpplint
- [ ] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by lroberts36 — APPROVED** [review]
LGTM, thanks for figuring out a fix.

**Comment by lroberts36** [comment]
@brryan: Maybe this is also a good pull request to remove the lower bound checks in `sort.hpp` (at lines 37, 39, 67, 69) since they give lots of compiler warnings since `size_t min_idx` is guaranteed to satisfy `min_idx >= 0` since it is unsigned. 

https://github.com/lanl/parthenon/blob/1ee26b74e67870904292b5fafb25ad3fbfad498e/src/utils/sort.hpp#L37

**Comment by brryan** [comment]
> @brryan: Maybe this is also a good pull request to remove the lower bound checks in `sort.hpp` (at lines 37, 39, 67, 69) since they give lots of compiler warnings since `size_t min_idx` is guaranteed to satisfy `min_idx >= 0` since it is unsigned.
> 
> https://github.com/lanl/parthenon/blob/1ee26b74e67870904292b5fafb25ad3fbfad498e/src/utils/sort.hpp#L37

Good point, fixed :+1:

**Review by pgrete — APPROVED** [review]
Good catch/hunch @lroberts36 and @brryan 
LGTM!

**Pull request merged**
