### PR TITLE
add missing include guard for hdf5 restart

### LINKED ISSUE #1094: Broken disabled HDF5 builds
The latest PR was missing some `#ifdef`'s to keep non-HDF5 builds working. when compiling with `PARTHENON_DISABLE_HDF5=ON` I get this error while building:
```
/home/scratch.fglines_gpu/projects/ats-5-benchmarks/parthenon/src/outputs/restart_hdf5.cpp: In member function 'virtual parthenon::RestartReader::MeshInfo parthenon::RestartReaderHDF5::GetMeshInfo() const':
/home/scratch.fglines_gpu/projects/ats-5-benchmarks/parthenon/src/outputs/restart_hdf5.cpp:138:38: error: 'fh_' was not declared in this scope
  138 |       PARTHENON_HDF5_CHECK(H5Lexists(fh_, "Blocks/derefinement_count", H5P_DEFAULT));
      |                                      ^~~
/home/scratch.fglines_gpu/projects/ats-5-benchmarks/parthenon/src/outputs/restart_hdf5.cpp:138:72: error: 'H5P_DEFAULT' was not declared in this scope; did you mean 'RTLD_DEFAULT'?
  138 |       PARTHENON_HDF5_CHECK(H5Lexists(fh_, "Blocks/derefinement_count", H5P_DEFAULT));
      |                                                                        ^~~~~~~~~~~
      |                                                                        RTLD_DEFAULT
/home/scratch.fglines_gpu/projects/ats-5-benchmarks/parthenon/src/outputs/restart_hdf5.cpp:138:28: error: 'H5Lexists' was not declared in this scope
  138 |       PARTHENON_HDF5_CHECK(H5Lexists(fh_, "Blocks/derefinement_count", H5P_DEFAULT));
      |                            ^~~~~~~~~
/home/scratch.fglines_gpu/projects/ats-5-benchmarks/parthenon/src/outputs/restart_hdf5.cpp:138:7: error: 'PARTHENON_HDF5_CHECK' was not declared in this scope; did you mean 'PARTHENON_MPI_CHECK'?
  138 |       PARTHENON_HDF5_CHECK(H5Lexists(fh_, "Blocks/derefinement_count", H5P_DEFAULT));
      |       ^~~~~~~~~~~~~~~~~~~~
      |       PARTHENON_MPI_CHECK
 ```

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Summary

This adds the missing preprocessor macro that should let us build with disabled HDF5. Resolves #1094 

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by pdmullen — APPROVED** [review]
LGTM

**Review by pgrete — APPROVED** [review]
My bad. Missed those when refactoring restarts.

Thanks!

**Review by lroberts36 — APPROVED** [review]
LGTM

**Comment by fglines-nv** [comment]
A bit late to the party, but can confirm, this fixed the build issues.

**Pull request merged**
