### PR TITLE
Fix HIP backend (and extend build coverage)

### LINKED ISSUE #647: Clang/Thrust sort issue
Showed up in new testing env https://github.com/lanl/parthenon/pull/629

Any clue what's going on @brryan ?

```
$ cmake -DKokkos_ENABLE_CUDA=ON -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_CXX_FLAGS=-Wno-unknown-cuda-version -Bbuild-clang-cu-old -S. -DKokkos_ARCH_VOLTA70=ON

[...] build

[ 56%] Building CXX object tst/unit/CMakeFiles/unit_tests.dir/test_unit_sort.cpp.o
In file included from /src/parthenon/tst/unit/test_unit_sort.cpp:25:
In file included from /src/parthenon/src/utils/sort.hpp:27:
In file included from /usr/local/cuda/include/thrust/sort.h:1361:
In file included from /usr/local/cuda/include/thrust/detail/sort.inl:26:
In file included from /usr/local/cuda/include/thrust/system/detail/generic/sort.h:153:
In file included from /usr/local/cuda/include/thrust/system/detail/generic/sort.inl:26:
In file included from /usr/local/cuda/include/thrust/find.h:384:
In file included from /usr/local/cuda/include/thrust/detail/find.inl:25:
In file included from /usr/local/cuda/include/thrust/system/detail/generic/find.h:62:
In file included from /usr/local/cuda/include/thrust/system/detail/generic/find.inl:19:
In file included from /usr/local/cuda/include/thrust/reduce.h:784:
In file included from /usr/local/cuda/include/thrust/detail/reduce.inl:26:
In file included from /usr/local/cuda/include/thrust/system/detail/generic/reduce_by_key.h:88:
In file included from /usr/local/cuda/include/thrust/system/detail/generic/reduce_by_key.inl:35:
In file included from /usr/local/cuda/include/thrust/scan.h:1563:
In file included from /usr/local/cuda/include/thrust/detail/scan.inl:29:
In file included from /usr/local/cuda/include/thrust/system/detail/adl/scan_by_key.h:42:
In file included from /usr/local/cuda/include/thrust/system/cuda/detail/scan_by_key.h:34:
In file included from /usr/local/cuda/include/thrust/system/cuda/execution_policy.h:81:
In file included from /usr/local/cuda/include/thrust/system/cuda/detail/sort.h:36:
In file included from /usr/local/cuda/include/cub/device/device_radix_sort.cuh:40:
In file included from /usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:40:
In file included from /usr/local/cuda/include/cub/device/dispatch/../../agent/agent_radix_sort_histogram.cuh:38:
/usr/local/cuda/include/cub/block/radix_rank_sort_operations.cuh:124:20: error: explicit qualification required to use member 'ProcessFloatMinusZero' from dependent base class
        return BFE(ProcessFloatMinusZero(key), bit_start, num_bits);
                   ^
/usr/local/cuda/include/cub/block/block_radix_rank.cuh:413:50: note: in instantiation of member function 'cub::BFEDigitExtractor<int>::Digit' requested here
            unsigned int digit = digit_extractor.Digit(keys[ITEM]);
                                                 ^
/usr/local/cuda/include/cub/device/dispatch/../../block/block_radix_sort.cuh:228:72: note: in instantiation of function template specialization 'cub::BlockRadixRank<256, 6, false, true, cub::BLOCK_SCAN_WARP_SCANS, cudaSharedMemBankSizeFourByte, 1, 1, 700>::RankKeys<unsigned int, 19, cub::BFEDigitExtractor<int>>' requested here
        AscendingBlockRadixRank(temp_storage.asending_ranking_storage).RankKeys(
                                                                       ^
/usr/local/cuda/include/cub/device/dispatch/../../block/block_radix_sort.cuh:367:13: note: in instantiation of member function 'cub::BlockRadixSort<int, 256, 19, cub::NullType, 6, true, cub::BLOCK_SCAN_WARP_SCANS, cudaSharedMemBankSizeFourByte, 1, 1, 700>::RankKeys' requested here
            RankKeys(unsigned_keys, ranks, digit_extractor, is_descending);
            ^
/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:327:40: note: in instantiation of function template specialization 'cub::BlockRadixSort<int, 256, 19, cub::NullType, 6, true, cub::BLOCK_SCAN_WARP_SCANS, cudaSharedMemBankSizeFourByte, 1, 1, 700>::SortBlockedToStriped<0, 1>' requested here
    BlockRadixSortT(temp_storage.sort).SortBlockedToStriped(
                                       ^
/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:1562:17: note: in instantiation of function template specialization 'cub::DeviceRadixSortSingleTileKernel<cub::DeviceRadixSortPolicy<int, cub::NullType, int>::Policy800, false, int, cub::NullType, int>' requested here
                DeviceRadixSortSingleTileKernel<MaxPolicyT, IS_DESCENDING, KeyT, ValueT, OffsetT>);
                ^
/usr/local/cuda/include/cub/device/dispatch/../../util_device.cuh:706:28: note: (skipping 14 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
        return op.template Invoke<PolicyT>();
                           ^
/usr/local/cuda/include/thrust/detail/sort.inl:41:10: note: in instantiation of function template specialization 'thrust::cuda_cub::sort<thrust::cuda_cub::tag, thrust::device_ptr<int>>' requested here
  return sort(thrust::detail::derived_cast(thrust::detail::strip_const(exec)), first, last);
         ^
/usr/local/cuda/include/thrust/detail/sort.inl:215:18: note: in instantiation of function template specialization 'thrust::sort<thrust::cuda_cub::tag, thrust::device_ptr<int>>' requested here
  return thrust::sort(select_system(system), first, last);
                 ^
/src/parthenon/src/utils/sort.hpp:63:11: note: in instantiation of function template specialization 'thrust::sort<thrust::device_ptr<int>>' requested here
  thrust::sort(first_d, last_d);
          ^
/src/parthenon/src/utils/sort.hpp:80:3: note: in instantiation of function template specialization 'parthenon::sort<int>' requested here
  sort(data, 0, data.extent(0) - 1);
  ^
/src/parthenon/tst/unit/test_unit_sort.cpp:61:5: note: in instantiation of function template specialization 'parthenon::sort<int>' requested here
    sort(data);
    ^
/usr/local/cuda/include/cub/block/radix_rank_sort_operations.cuh:98:52: note: member is declared here
    static __device__ __forceinline__ UnsignedBits ProcessFloatMinusZero(UnsignedBits key)
                                                   ^
/usr/local/cuda/include/cub/block/radix_rank_sort_operations.cuh:143:25: error: explicit qualification required to use member 'ProcessFloatMinusZero' from dependent base class
        return uint32_t(ProcessFloatMinusZero(key) >> UnsignedBits(bit_start)) & mask;
                        ^
/usr/local/cuda/include/cub/device/dispatch/../../agent/agent_radix_sort_histogram.cuh:194:43: note: in instantiation of member function 'cub::ShiftDigitExtractor<int>::Digit' requested here
                int bin = digit_extractor.Digit(keys[u]);
                                          ^
/usr/local/cuda/include/cub/device/dispatch/../../agent/agent_radix_sort_histogram.cuh:231:13: note: in instantiation of member function 'cub::AgentRadixSortHistogram<cub::AgentRadixSortHistogramPolicy<256, 8, 8, int, 8>, false, int, int>::AccumulateSharedHistograms' requested here
            AccumulateSharedHistograms(tile_offset, keys);
            ^
/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:536:11: note: in instantiation of member function 'cub::AgentRadixSortHistogram<cub::AgentRadixSortHistogramPolicy<256, 8, 8, int, 8>, false, int, int>::Process' requested here
    agent.Process();
          ^
/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:1314:37: note: in instantiation of function template specialization 'cub::DeviceRadixSortHistogramKernel<cub::DeviceRadixSortPolicy<int, cub::NullType, int>::Policy800, false, int, int>' requested here
            auto histogram_kernel = DeviceRadixSortHistogramKernel<
                                    ^
/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:1546:16: note: in instantiation of function template specialization 'cub::DispatchRadixSort<false, int, cub::NullType, int>::InvokeOnesweep<cub::DeviceRadixSortPolicy<int, cub::NullType, int>::Policy600>' requested here
        return InvokeOnesweep<ActivePolicyT>();
               ^
/usr/local/cuda/include/cub/device/dispatch/dispatch_radix_sort.cuh:1567:20: note: (skipping 13 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
            return InvokeManyTiles<ActivePolicyT>(Int2Type<ActivePolicyT::ONESWEEP>());
                   ^
/usr/local/cuda/include/thrust/detail/sort.inl:41:10: note: in instantiation of function template specialization 'thrust::cuda_cub::sort<thrust::cuda_cub::tag, thrust::device_ptr<int>>' requested here
  return sort(thrust::detail::derived_cast(thrust::detail::strip_const(exec)), first, last);
         ^
/usr/local/cuda/include/thrust/detail/sort.inl:215:18: note: in instantiation of function template specialization 'thrust::sort<thrust::cuda_cub::tag, thrust::device_ptr<int>>' requested here
  return thrust::sort(select_system(system), first, last);
                 ^
/src/parthenon/src/utils/sort.hpp:63:11: note: in instantiation of function template specialization 'thrust::sort<thrust::device_ptr<int>>' requested here
  thrust::sort(first_d, last_d);
          ^
/src/parthenon/src/utils/sort.hpp:80:3: note: in instantiation of function template specialization 'parthenon::sort<int>' requested here
  sort(data, 0, data.extent(0) - 1);
  ^
/src/parthenon/tst/unit/test_unit_sort.cpp:61:5: note: in instantiation of function template specialization 'parthenon::sort<int>' requested here
    sort(data);
    ^
/usr/local/cuda/include/cub/block/radix_rank_sort_operations.cuh:98:52: note: member is declared here
    static __device__ __forceinline__ UnsignedBits ProcessFloatMinusZero(UnsignedBits key)
                                                   ^
2 errors generated when compiling for sm_70.
make[2]: *** [tst/unit/CMakeFiles/unit_tests.dir/build.make:154: tst/unit/CMakeFiles/unit_tests.dir/test_unit_sort.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1664: tst/unit/CMakeFiles/unit_tests.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

### PR DESCRIPTION
**Pull request by pgrete**
## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by pgrete** [comment]
This is now ready for review.
I decided to not add SYCL for now due to lack of hardware. But I added a warning to say that the backend is not tested.

Test suite passes on an MI100 system:
Unit:
```
ctest -LE 'performance|regression'
Test project /parthenon/build-hip
      Start  1: unit_tests:Adding MeshBlockData objects to a DataCollection
 1/33 Test  #1: unit_tests:Adding MeshBlockData objects to a DataCollection ........   Passed    0.68 sec
      Start  2: unit_tests:Just check everything
 2/33 Test  #2: unit_tests:Just check everything ...................................   Passed    0.65 sec
      Start  3: unit_tests:Task Object Lifecycle
 3/33 Test  #3: unit_tests:Task Object Lifecycle ...................................   Passed    0.64 sec
      Start  4: unit_tests:Can create a vector-valued face-variable
 4/33 Test  #4: unit_tests:Can create a vector-valued face-variable ................   Passed    0.65 sec
      Start  5: unit_tests:Add, Get, and Update are called
 5/33 Test  #5: unit_tests:Add, Get, and Update are called .........................   Passed    0.65 sec
      Start  6: unit_tests:reset is called
 6/33 Test  #6: unit_tests:reset is called .........................................   Passed    0.64 sec
      Start  7: unit_tests:when hasKey is called
 7/33 Test  #7: unit_tests:when hasKey is called ...................................   Passed    0.64 sec
      Start  8: unit_tests:Physical constants
 8/33 Test  #8: unit_tests:Physical constants ......................................   Passed    0.64 sec
      Start  9: unit_tests:Checking IndexShape indices
 9/33 Test  #9: unit_tests:Checking IndexShape indices .............................   Passed    0.64 sec
      Start 10: unit_tests:Checking IndexShape cell counts
10/33 Test #10: unit_tests:Checking IndexShape cell counts .........................   Passed    0.64 sec
      Start 11: unit_tests:Sorting
11/33 Test #11: unit_tests:Sorting .................................................   Passed    0.64 sec
      Start 12: unit_tests:par_for loops
12/33 Test #12: unit_tests:par_for loops ...........................................   Passed    1.40 sec
      Start 13: unit_tests:nested par_for loops
13/33 Test #13: unit_tests:nested par_for loops ....................................   Passed    0.71 sec
      Start 15: unit_tests:Device Object Allocation
14/33 Test #15: unit_tests:Device Object Allocation ................................   Passed    0.65 sec
      Start 16: unit_tests:Built-in flags are registered
15/33 Test #16: unit_tests:Built-in flags are registered ...........................   Passed    0.64 sec
      Start 17: unit_tests:A Metadata flag is allocated
16/33 Test #17: unit_tests:A Metadata flag is allocated ............................   Passed    0.64 sec
      Start 18: unit_tests:A Metadata struct is created
17/33 Test #18: unit_tests:A Metadata struct is created ............................   Passed    0.65 sec
      Start 19: unit_tests:ParArrayND
18/33 Test #19: unit_tests:ParArrayND ..............................................   Passed    0.66 sec
      Start 20: unit_tests:ParArrayND with LayoutLeft
19/33 Test #20: unit_tests:ParArrayND with LayoutLeft ..............................   Passed    0.66 sec
      Start 21: unit_tests:ParArray resizing
20/33 Test #21: unit_tests:ParArray resizing .......................................   Passed    0.51 sec
      Start 25: unit_tests:Can pull variables from containers based on Metadata
21/33 Test #25: unit_tests:Can pull variables from containers based on Metadata ....   Passed    0.68 sec
      Start 26: unit_tests:Coarse variable from meshblock_data for cell variable
22/33 Test #26: unit_tests:Coarse variable from meshblock_data for cell variable ...   Passed    0.65 sec
      Start 27: unit_tests:Get the correct access pattern when using FlatIdx
23/33 Test #27: unit_tests:Get the correct access pattern when using FlatIdx .......   Passed    0.66 sec
      Start 28: unit_tests:MeshData works as expected for simple packs
24/33 Test #28: unit_tests:MeshData works as expected for simple packs .............   Passed    0.67 sec
      Start 29: unit_tests:Swarm memory management
25/33 Test #29: unit_tests:Swarm memory management .................................   Passed    0.68 sec
      Start 30: unit_tests:Test required/desired checking from inputs
26/33 Test #30: unit_tests:Test required/desired checking from inputs ..............   Passed    0.64 sec
      Start 31: unit_tests:Parthenon Error Checking
27/33 Test #31: unit_tests:Parthenon Error Checking ................................   Passed    0.64 sec
      Start 32: unit_tests:Check that integer division, rounded up, works
28/33 Test #32: unit_tests:Check that integer division, rounded up, works ..........   Passed    0.64 sec
      Start 33: unit_tests:Check that partitioning a container works
29/33 Test #33: unit_tests:Check that partitioning a container works ...............   Passed    0.65 sec
      Start 34: unit_tests:Test Add/Get in Packages_t
30/33 Test #34: unit_tests:Test Add/Get in Packages_t ..............................   Passed    0.64 sec
      Start 35: unit_tests:Test Associate in StateDescriptor
31/33 Test #35: unit_tests:Test Associate in StateDescriptor .......................   Passed    0.64 sec
      Start 36: unit_tests:Test dependency resolution in StateDescriptor
32/33 Test #36: unit_tests:Test dependency resolution in StateDescriptor ...........   Passed    0.64 sec
      Start 37: unit_tests:Test SparsePool interface
33/33 Test #37: unit_tests:Test SparsePool interface ...............................   Passed    0.64 sec

100% tests passed, 0 tests failed out of 33

Label Time Summary:
add,get,update           =   0.65 sec*proc (1 test)
addtask                  =   0.64 sec*proc (1 test)
cgs                      =   0.64 sec*proc (1 test)
checkdependencies        =   0.65 sec*proc (1 test)
constructor              =   0.65 sec*proc (1 test)
datacollection           =   0.68 sec*proc (1 test)
equal                    =   0.65 sec*proc (1 test)
errorchecking            =   0.64 sec*proc (1 test)
facevariable             =   0.65 sec*proc (1 test)
flatidx                  =   0.66 sec*proc (1 test)
get                      =   0.65 sec*proc (1 test)
haskey                   =   0.64 sec*proc (1 test)
indexshape               =   1.29 sec*proc (2 tests)
intceil                  =   0.64 sec*proc (1 test)
kokkos                   =   1.96 sec*proc (3 tests)
layoutleft               =   0.66 sec*proc (1 test)
meshblockdataiterator    =   1.33 sec*proc (2 tests)
meshdata                 =   0.67 sec*proc (1 test)
metadata                 =   1.93 sec*proc (3 tests)
or                       =   0.65 sec*proc (1 test)
packages_t               =   0.64 sec*proc (1 test)
parameterinput           =   0.64 sec*proc (1 test)
pararraynd               =   1.83 sec*proc (3 tests)
partition                =   0.65 sec*proc (1 test)
reset                    =   0.64 sec*proc (1 test)
set                      =   0.65 sec*proc (1 test)
setfinished              =   0.65 sec*proc (1 test)
si                       =   0.64 sec*proc (1 test)
sort                     =   0.64 sec*proc (1 test)
statedescriptor          =   1.92 sec*proc (3 tests)
swarm                    =   0.68 sec*proc (1 test)
tasklist                 =   0.64 sec*proc (1 test)
unit_tests               =  22.12 sec*proc (33 tests)
wrapper                  =   2.76 sec*proc (3 tests)

Total Test time (real) =  22.19 sec
```

Regression:
```
$ ctest -L "performance|regression" -LE "mpi-yes|perf-reg"
Test project /parthenon/build-hip
      Start 14: unit_tests:Overlapping SpaceInstances
 1/15 Test #14: unit_tests:Overlapping SpaceInstances .....................   Passed    0.72 sec
      Start 22: unit_tests:Time simple stencil operations
 2/15 Test #22: unit_tests:Time simple stencil operations .................   Passed    0.66 sec
      Start 23: unit_tests:Check registry pressure
 3/15 Test #23: unit_tests:Check registry pressure ........................   Passed    1.48 sec
      Start 24: unit_tests:Check many arrays
 4/15 Test #24: unit_tests:Check many arrays ..............................   Passed    0.69 sec
      Start 38: performance_tests:Catch2 Container Iterator Performance
 5/15 Test #38: performance_tests:Catch2 Container Iterator Performance ...   Passed   11.55 sec
      Start 41: regression_test:particle_leapfrog
 6/15 Test #41: regression_test:particle_leapfrog .........................   Passed    2.56 sec
      Start 43: regression_test:particle_leapfrog_outflow
 7/15 Test #43: regression_test:particle_leapfrog_outflow .................   Passed    1.42 sec
      Start 45: regression_test:restart
 8/15 Test #45: regression_test:restart ...................................   Passed   76.44 sec
      Start 47: regression_test:calculate_pi
 9/15 Test #47: regression_test:calculate_pi ..............................   Passed    1.39 sec
      Start 49: regression_test:advection_convergence
10/15 Test #49: regression_test:advection_convergence .....................   Passed   81.86 sec
      Start 51: regression_test:output_hdf5
11/15 Test #51: regression_test:output_hdf5 ...............................   Passed   50.14 sec
      Start 53: regression_test:advection_outflow
12/15 Test #53: regression_test:advection_outflow .........................   Passed    3.39 sec
      Start 55: regression_test:bvals
13/15 Test #55: regression_test:bvals .....................................   Passed    3.43 sec
      Start 57: regression_test:poisson
14/15 Test #57: regression_test:poisson ...................................   Passed    4.92 sec
      Start 59: regression_test:sparse_advection
15/15 Test #59: regression_test:sparse_advection ..........................   Passed   52.36 sec

100% tests passed, 0 tests failed out of 15

Label Time Summary:
meshblockdataiterator    =  11.55 sec*proc (1 test)
mpi-no                   = 277.90 sec*proc (10 tests)
pararraynd               =   2.83 sec*proc (3 tests)
performance              =  15.11 sec*proc (5 tests)
performance_tests        =  11.55 sec*proc (1 test)
poisson                  =   4.92 sec*proc (1 test)
regression               = 277.90 sec*proc (10 tests)
unit_tests               =   3.55 sec*proc (4 tests)
wrapper                  =   0.72 sec*proc (1 test)

Total Test time (real) = 293.05 sec
```

**Review by Yurlungur — APPROVED** [review]
Big fan of the github workflow clang test, and the cmake file for github actions.

**Comment by pgrete** [comment]
- [x] update to clang 13

**Comment by pgrete** [comment]
I just bumped to clang (and the Dockerfile) to v13. This did not fix the "sort" related compile issues with cuda/clang, see #647
How shall we proceed? @Yurlungur @brryan

**Comment by pgrete** [comment]
I now implemented the fix we discussed yesterday (i.e., removing the calls to thrust::sort for cuda/clang) and added a very verbose output in case people need it.

@forrestglines would you mind giving this a brief review.

**Review by brryan — APPROVED** [review]
LGTM

**Comment by pgrete** [comment]
Great. Two approvals. Pulling the trigger.

**Pull request merged**
