### PR TITLE
Joshua s brown/version 0.4

### LINKED ISSUE #414: Release 0.4

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
## PR Checklist

Officially creates version 0.4. 

- [x] Code passes cpplint
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
Darwin CI run: https://re-git.lanl.gov/eap-oss/parthenon/-/jobs/94834

**Review by Yurlungur — APPROVED** [review]

**Comment by JoshuaSBrown** [comment]
@pgrete @AndrewGaspar I cannot merge this until I get approvals.

**Review by AndrewGaspar — APPROVED** [review]

**Comment by AndrewGaspar** [comment]
Oops, sorry about that!

**Comment by JoshuaSBrown** [comment]
@pgrete Are you happy with merging this?

**Pull request merged**
