### PR TITLE
[WIP] Make parthenon input class methods DRY

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
## PR Summary

This pr is incomplete, submitting to test triggering of CI. 

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by Yurlungur** [comment]
This is a good idea... but will be API breaking. Perhaps we could leave the old API in place also, but it just calls the templated version?

**Comment by JoshuaSBrown** [comment]
> This is a good idea... but will be API breaking. Perhaps we could leave the old API in place also, but it just calls the templated version?

That's reasonable, what about if I added deprecated to the old methods to encourage switching over without breaking. The template api will be cleaner.

**Comment by Yurlungur** [comment]
> what about if I added deprecated to the old methods to encourage switching over without breaking

What did you have in mind? A comment above each method saying its deprecated makes sense to me. I would advise against adding a runtime warning, as that will make simulation output difficult to read.

**Comment by JoshuaSBrown** [comment]
> > what about if I added deprecated to the old methods to encourage switching over without breaking
> 
> What did you have in mind? A comment above each method saying its deprecated makes sense to me. I would advise against adding a runtime warning, as that will make simulation output difficult to read.

No, compile time 
```
[[deprecated]]
```
https://en.cppreference.com/w/cpp/language/attributes/deprecated

**Comment by Yurlungur** [comment]
> > > what about if I added deprecated to the old methods to encourage switching over without breaking
> > 
> > 
> > What did you have in mind? A comment above each method saying its deprecated makes sense to me. I would advise against adding a runtime warning, as that will make simulation output difficult to read.
> 
> No, compile time
> 
> ```
> [[deprecated]]
> ```
> 
> https://en.cppreference.com/w/cpp/language/attributes/deprecated

Oh cool. I wasn't aware of that feature. Yep that makes sense to me.

**Comment by jlippuner** [comment]
Will revisit if needed

**Pull request closed without merging**
