### PR TITLE
New action: check PR dependencies & warn until requirements merged

### PR DESCRIPTION
**Pull request by c-prather**
Add a Github action which checks dependencies between PRs.  Should fail until all required PRs are merged.

Action repository is here: https://github.com/gregsdennis/dependencies-action

The required access token need cover only reading pull requests and issues, which are public anyway.  It keys on any dependencies mentioned in the opening comment, e.g.

Depends on #772

### CODE REVIEW

**Comment by Yurlungur** [comment]
@bprather can you try re-triggering the CI on this, maybe by making a quick change or something? I believe I have fixed the permissions issue.

**Comment by c-prather** [comment]
Check failed successfully.

**Review by Yurlungur — CHANGES_REQUESTED** [review]
Excellent. Can you update the changelog? Then if we can remove the dependency, we should get another approval and merge this bad boy in. :)

**Comment by Yurlungur** [comment]
Pinging @lroberts36 @pgrete for review

**Review by lroberts36 — APPROVED** [review]
LGTM, seems like it is working!

**Review by Yurlungur — APPROVED** [review]
Oops didn't realize I hadn't approved. LGTM. :+1:

**Pull request merged**
