### PR TITLE
Add cycle and nbtotal to hst

### PR DESCRIPTION
**Pull request by pdmullen**
## PR Summary
This PR adds the cycle and total number of MeshBlocks to the history file output.  If we choose to merge this one, please merge it after #1127.

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] Change is breaking (API, behavior, ...)
  - [x] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [x] PR is marked as breaking
  - [x] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] Docs build
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
:+1: Two things:
1. Can you make sure that the isntrucitons for checking correctness in `benchmark/burgers` still work?
2. Make sure this only goes in after #1127

**Comment by pdmullen** [comment]
> 👍 Two things:
> 
> 1. Can you make sure that the isntrucitons for checking correctness in `benchmark/burgers` still work?
> 2. Make sure this only goes in after [Add WithFluxes to IsRefined check #1127](https://github.com/parthenon-hpc-lab/parthenon/pull/1127)

Just went through the `benchmark/burgers` test.  It looks like it was shipping its own custom `nbtotal` reduction.  I eliminated this since this data is now outputted to `hst` by default.  The new history files are compatible with the `burgers_diff.py` script, however, I'd note that this script had a bug in it such that no diffs would ever actually be reported --- fixed now.

**Comment by Yurlungur** [comment]
> > 👍 Two things:
> > 
> > 1. Can you make sure that the isntrucitons for checking correctness in `benchmark/burgers` still work?
> > 2. Make sure this only goes in after [Add WithFluxes to IsRefined check #1127](https://github.com/parthenon-hpc-lab/parthenon/pull/1127)
> 
> Just went through the `benchmark/burgers` test. It looks like it was shipping its own custom `nbtotal` reduction. I eliminated this since this data is now outputted to `hst` by default. The new history files are compatible with the `burgers_diff.py` script, however, I'd note that this script had a bug in it such that no diffs would ever actually be reported --- fixed now.

Thanks @pdmullen !

**Review by brryan — APPROVED** [review]
LGTM :+1:

**Pull request merged**
