### PR TITLE
Add a Codacy badge to README.md

### PR DESCRIPTION
**Pull request by codacy-badger**
Adds a badge to the README to display the code quality.

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]

**Review by AndrewGaspar — APPROVED** [review]

**Comment by JoshuaSBrown** [comment]
I cannot merge this because the ci will not trigger since Codacy is the owner of pr, but the ci is not really needed for this anyway. @AndrewGaspar can we override the tests in this case? Pending @pgrete has no objections to this badge.

**Comment by pgrete** [comment]
Is this (the checks not the badge) actually working?
When I go on the Codacy link I see the following error "We can't analyze your pull requests because the GitHub integration is disabled. Please ask an administrator of this repository to enable the integration."

**Comment by JoshuaSBrown** [comment]
> Is this (the checks not the badge) actually working?
> When I go on the Codacy link I see the following error "We can't analyze your pull requests because the GitHub integration is disabled. Please ask an administrator of this repository to enable the integration."

Did you switch to the develop branch after hitting the link, the default results it loads is add_mesh_integration_test?

Ok, nevermind still getting that message. @AndrewGaspar was this because we were going to wait to turn it on after you sanitized the repo?

**Comment by JoshuaSBrown** [comment]
I'm going to go ahead and merge this I fixed the permissions issue. This is just a cosmetic pr.

**Pull request merged**
