### PR TITLE
Use power9 partition for Darwin CI

### PR DESCRIPTION
**Pull request by sfogerty**
## PR Summary

`power9-eap-ci` is a computing resource on Darwin with access only for EAP devs, so for some Parthenon folks this Darwin CI will fail because they lack the required permissions. It's probably more appropriate to run this CI in the `power9` Darwin partition.

@jonahm-LANL @JoshuaSBrown 

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by lroberts36** [comment]
The darwin admins confirmed it was ok to use the regular `power9` partition for the Parthenon CI.

**Review by lroberts36 — APPROVED** [review]
LGTM

**Review by Yurlungur — APPROVED** [review]
If Darwin admins say it's ok it's ok by me

**Comment by Yurlungur** [comment]
@sfogerty can you add this PR to the CHANGELOG.md file?

**Comment by Yurlungur** [comment]
One of us should also trigger it on Darwin to make sure it works as expected.

**Pull request merged**
