### PR TITLE
WIP: Fix performance regression

### PR DESCRIPTION
**Pull request by pgrete**
## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md

### CODE REVIEW

**Comment by pgrete** [comment]
Still WIP as I'm still not back at the expected level of performance.

**Comment by pgrete** [comment]
Ready for review.
The big piece is the missing reference in the FluxDivergence, which significantly affected performance.
For a single 128^3 MeshBlock on an AVX512 core
`develop`: `|-> 1.85e+00 sec 67.4% 0.0% 0.0% 100.0% 0.00e+00 20 FluxDivergenceMesh [region]`
this PR: `|-> 1.17e-01 sec 11.9% 0.0% 0.0% 100.0% 0.00e+00 20 FluxDivergenceMesh [region]`

The templated inline reconstruction function make them work with `ParArrayND`s, `ParArray#D`s, `VarPacks` etc.

**Review by Yurlungur — APPROVED** [review]
Thanks for the catch.

**Comment by jdolence** [comment]
@pgrete, just a quick note that this PR has a conflict now because of the updates from #358

**Comment by pgrete** [comment]
Yes, and also not applicable anymore given that the performance issues have been addressed.
I may update this one to only include the reconstruction changes or let go of it completely (depending on the downstream changes).
Turning this WIP for now

**Comment by pgrete** [comment]
Closed via #358 and #359

**Pull request closed without merging**
