### PR TITLE
update to Kokkos 4.0.1

### LINKED ISSUE #842: Kokkos 4.0.0 / CUDA 12 support?
Are there any deprecated features or anything else blocking moving to Kokkos 4.0.0?

### PR DESCRIPTION
**Pull request by BenWibking**
## PR Summary

Upgrades the built-in Kokkos submodule to Kokkos 4. This is needed for Frontier, Chicoma, possibly other machines.

Closes https://github.com/parthenon-hpc-lab/parthenon/issues/842.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by BenWibking** [comment]
The HIP tests are failing because we need ROCm >= 5.2 for Kokkos 4:

```
CMake Error at external/Kokkos/cmake/kokkos_compiler_id.cmake:194 (MESSAGE):
  Compiler not supported by Kokkos.  Required compiler versions:

      Clang(CPU)         8.0.0 or higher
      Clang(CUDA)       10.0.0 or higher
      GCC                8.2.0 or higher
      Intel             19.0.5 or higher
      IntelLLVM(CPU)  2021.1.1 or higher
      IntelLLVM(SYCL) 2022.0.0 or higher
      NVCC              11.0.0 or higher
      HIPCC              5.2.0 or higher
      NVHPC/PGI           22.3 or higher
      MSVC               19.29 or higher
      XL/XLClang           not supported

  Compiler: HIPCC 4.4.21401
  ```

**Review by Yurlungur — APPROVED** [review]
Do we need to change anything in the cmake? Or is it enough to update the submodule? Are the ROCM dependencies modern enough we can rely on them?

**Comment by BenWibking** [comment]
> Do we need to change anything in the cmake? Or is it enough to update the submodule? Are the ROCM dependencies modern enough we can rely on them?

I was hoping @pgrete might answer these questions based on building on Frontier :)

**Comment by BenWibking** [comment]
It looks like we need a newer ROCm container image:
https://github.com/parthenon-hpc-lab/parthenon/blob/6487af5b5db437ecf886a9d97076220f964be7f0/.github/workflows/check-compilers.yml#L56

**Comment by BenWibking** [comment]
> It looks like we need a newer ROCm container image:
> 
> https://github.com/parthenon-hpc-lab/parthenon/blob/6487af5b5db437ecf886a9d97076220f964be7f0/.github/workflows/check-compilers.yml#L56

@pgrete @Yurlungur would it make sense to use a "standard" ROCm container, such as this one provided by AMD for ROCm 5.3: https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/rocm-terminal/Dockerfile

**Comment by Yurlungur** [comment]
I defer to @pgrete on this one

**Comment by pgrete** [comment]
I'll take care of an image update (when I'm actually back at my desk tomorrow after 2.5 weeks of conferences/workshops)

**Comment by pgrete** [comment]
I updated the other infrastructure related pieces.

**Review by pgrete — APPROVED** [review]

**Comment by pgrete** [comment]
Now I am confused. Looks like our compiler checks not mandatory to pass in order to trigger auto-merge.
I'll fix this in a follow up PR and we can ignore this for now.

**Pull request merged**
