### PR TITLE
Fix restarting from files with ghost zones

### PR DESCRIPTION
**Pull request by c-prather**
## PR Summary

Fix an old issue when restarting from files written including ghost zones (i.e., setting ghost_zones=true in the restart file block).

This is clearly not a common usage, but it's nice for Dirichlet boundary conditions -- as well as some old versions of KHARMA, which included ghosts in restart files for esoteric reasons related to recovering primitive variables.

We could regression-test this by enabling ghost_zones=true in one or another restarting test -- I'm not sure where or I'd go ahead.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by c-prather** [comment]
@par-hermes format

**Review by Yurlungur — APPROVED** [review]
Assuming tests pass and you add a changelog I'm fine with this change. Might be worth running by the athenak folks too. @pgrete @forrestglines

**Comment by pgrete** [comment]
Does this mean that the `MeshBlockSize` currently stored in the output file with ghost zones is not the actual "block" size, but the data size?

**Comment by c-prather** [comment]
Yes, the block size recorded includes ghosts if they're enabled -- I don't think this is a huge problem, though it is unintuitive (not to mention redundant with the HDF5 dataset dimensions, I think).  I went with the reader fix to avoid changing the file format, but we should document somewhere that that's how it is.

BTW still happy to record ghosts in one of the restart-based tests, just don't know my way around the infrastructure.  The current tests won't really exercise the new code, since no restarts include ghosts.

**Comment by c-prather** [comment]
Failing check is FindFilesystem.cmake.  I think the correct notice is added in Luke's first PR, so as soon as it goes in I can pull & pass the check.

The `perf-and-regression` tests appear to be stalled on all outstanding PRs though?

**Review by pgrete — APPROVED** [review]
While I think that the design/the content in the output should be updated, i.e., block sizes are the block sizes without ghost zones and the dimensions are being derived from `IncludesGhost`, this is not that important to be fixed now.
So I'm happy to approve without test (however, feel free to add a node to the doc that writing/restart from ghosts is untested/unsupported/only for debugging).

**Comment by pgrete** [comment]
> The `perf-and-regression` tests appear to be stalled on all outstanding PRs though?

The more expensive test suite is only triggered once "auto-merge" is enabled.
If you want to force it you can either triggered through the Actions tab manually, or briefly enable/disable auto-merge (as I just did).

**Review by lroberts36 — APPROVED** [review]
LGTM

**Comment by Yurlungur** [comment]
@bprather can you clean up formatting then we merge?

**Comment by c-prather** [comment]
Oh this is the copyright thing I inherited from develop.  I'll copy the fix from Luke's PR.

Though, separately, I'm not sure I like pasting a big ol' (C) LANL atop someone else's copyright...

**Pull request merged**
