### PR TITLE
Fix call to nonexistent logger

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
## PR Summary

One of the python performance regression scripts was making a call to a logger which did not exist. This pr fixes the problem. 

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by jlippuner — APPROVED** [review]
Looks good. Would it make sense to make the logging level configurable, in case we want something other than `INFO` in some cases?

**Review by Yurlungur — APPROVED** [review]

**Review by pgrete — APPROVED** [review]
:+1: Also nice to see the performance app in practice (I clicked the working link)!

**Comment by JoshuaSBrown** [comment]
Thanks guys!

**Comment by JoshuaSBrown** [comment]
> Looks good. Would it make sense to make the logging level configurable, in case we want something other than `INFO` in some cases?

I will create an issue. Thought I had done this but I guess not.

**Comment by JoshuaSBrown** [comment]
@par-hermes format

**Pull request merged**
