### PR TITLE
Allow communication buffers in host pinned space

### PR DESCRIPTION
**Pull request by pgrete**
## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md

### CODE REVIEW

**Comment by pgrete** [comment]
This is ready for review. It introduces an easy switch to allocate buffers on the host (HostPinned is accessible from device and host). Some Kokkos test showed that this results in better performance (see Kokkos lecture on MPI) but I was not able to confirm this for Parthenon.
Nevertheless, I think that easy switch is a useful addition.

**Review by Yurlungur — APPROVED** [review]
Given how simple a change this is, I think it's a nice idea. Definitely something to experiment with.

**Comment by pgrete** [comment]
ping @AndrewGaspar

**Comment by pgrete** [comment]
@AndrewGaspar would you mind approving (you already reviewed these changes as part of the buffer in one where this branch was already pulled in) so that we can merge?

**Comment by AndrewGaspar** [comment]
oh, sorry, didn't realize this.

**Review by AndrewGaspar — APPROVED** [review]

**Pull request merged**
