### PR TITLE
Use subviews for buffers

### LINKED ISSUE #415: AMR performance 1/N: Single large comm buffers versus 100+ small ones
My current interpretation of profiling data on GPU suggests that (especially during load balance and mesh refinement) quite a bit of time is spent in allocating and deallocating comm buffers.
Current each buffer is is a separate Kokkos view, i.e., there are >100 (tiny) buffers for each MeshBlock.
This could be circumvented by using a single buffer with separate offsets.

### PR DESCRIPTION
**Pull request by pgrete**
## PR Summary

Before:

Screenshot from 2021-04-20 22-40-29

After:

Screenshot from 2021-04-20 22-42-49

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by Yurlungur** [comment]
Very elegant solution!

**Review by Yurlungur — APPROVED** [review]
I vote we get this into the hackathon integration branch ASAP

**Review by forrestglines — COMMENTED** [review]
Look good, we should merge it soon.

**Comment by Yurlungur** [comment]
Let's just pull the trigger then.

**Pull request merged**
