### PR TITLE
Update to latest Kokkos release

### PR DESCRIPTION
**Pull request by jdolence**
## PR Summary

Updating to Kokkos v3.4.1

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Approved. But we should make sure the full test suite passes before merging

**Review by jlippuner — APPROVED** [review]
Agree with @Yurlungur that we need to ensure all tests pass before merging

**Comment by Yurlungur** [comment]
Triggered the full test suite and it all passes. I think this is ready. Pinging @pgrete @forrestglines to see if they have any objections.

**Comment by jdolence** [comment]
Everything appears to pass so this should be ready to go in.  I'll give @pgrete and @forrestglines a chance to object, but will merge this in tomorrow if I don't hear anything.

**Review by pgrete — APPROVED** [review]
A very welcome change (AthenaPK already uses a more recent Kokkos version)

**Pull request merged**
