### PR TITLE
Make python file loading faster

### PR DESCRIPTION
**Pull request by c-prather**
Opening this to trigger tests/float quickly. Very small change but useful for downstream codes using phdf.py.

## PR Summary

Replaces a python nested loop with vectorized/numpy operations to reduce phdf.py's file open time from ~2s to trivial.  Necessary in some downstream code for treating Parthenon output.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
I don't fully understand this transformation but if the tests say it works I'm ok with that. Maybe @pgrete or @lroberts36 should take a look

**Comment by Yurlungur** [comment]
We should also add a CHANGELOG entry in CHANGELOG.md

**Comment by Yurlungur** [comment]
One more approval required. Pinging @jdolence @brryan @pgrete @forrestglines @lroberts36

**Review by brryan — APPROVED** [review]
Similar caveat about not actually compiling the new code in my head but if the tests pass I think this has to be OK. 

Approving now but do we understand why the darwin CI is failing here? Looks like it's trying to find something with cpp17 but I thought that PR wasnt merged yet.

**Review by pgrete — CHANGES_REQUESTED** [review]
As far as I can tell, this PR does change the order of the indices, e.g.,

```python
class Test:
    def __init__(self, mb_nx1, mb_nx2, mb_nx3):
        self.MeshBlockSize = (mb_nx1, mb_nx2, mb_nx3)
        self.CellsPerBlock = np.product(self.MeshBlockSize)
        
        xRange = range(self.MeshBlockSize[0])
        yRange = range(self.MeshBlockSize[1])
        zRange = range(self.MeshBlockSize[2])

        self.BlockIdx = [None] * self.CellsPerBlock
        self.isGhost = np.ones(self.CellsPerBlock, dtype=bool)
        index = 0
        yMask = False
        zMask = False
        for k in zRange:
            for j in yRange:
                for i in xRange:
                    self.BlockIdx[index] = [k, j, i]
                    index += 1
                    
        print(self.BlockIdx)
        
        self.BlockIdxNew = [None] * self.CellsPerBlock
        self.BlockIdxNew = np.reshape(
            np.array(np.meshgrid(zRange, yRange, xRange)).transpose(1, 2, 3, 0),
            (self.MeshBlockSize[0] * self.MeshBlockSize[1] * self.MeshBlockSize[2], 3),
        )
        print(self.BlockIdxNew)

Test(4,6,7)
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 0, 3], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 1, 3], [0, 2, 0], [0, 2, 1], [0, 2, 2], [0, 2, 3], [0, 3, 0], [0, 3, 1], [0, 3, 2], [0, 3, 3], [0, 4, 0], [0, 4, 1], [0, 4, 2], [0, 4, 3], [0, 5, 0], [0, 5, 1], [0, 5, 2], [0, 5, 3], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 0, 3], [1, 1, 0], [1, 1, 1], [1, 1, 2], [1, 1, 3], [1, 2, 0], [1, 2, 1], [1, 2, 2], [1, 2, 3], [1, 3, 0], [1, 3, 1], [1, 3, 2], [1, 3, 3], [1, 4, 0], [1, 4, 1], [1, 4, 2], [1, 4, 3], [1, 5, 0], [1, 5, 1], [1, 5, 2], [1, 5, 3], [2, 0, 0], [2, 0, 1], [2, 0, 2], [2, 0, 3], [2, 1, 0], [2, 1, 1], [2, 1, 2], [2, 1, 3], [2, 2, 0], [2, 2, 1], [2, 2, 2], [2, 2, 3], [2, 3, 0], [2, 3, 1], [2, 3, 2], [2, 3, 3], [2, 4, 0], [2, 4, 1], [2, 4, 2], [2, 4, 3], [2, 5, 0], [2, 5, 1], [2, 5, 2], [2, 5, 3], [3, 0, 0], [3, 0, 1], [3, 0, 2], [3, 0, 3], [3, 1, 0], [3, 1, 1], [3, 1, 2], [3, 1, 3], [3, 2, 0], [3, 2, 1], [3, 2, 2], [3, 2, 3], [3, 3, 0], [3, 3, 1], [3, 3, 2], [3, 3, 3], [3, 4, 0], [3, 4, 1], [3, 4, 2], [3, 4, 3], [3, 5, 0], [3, 5, 1], [3, 5, 2], [3, 5, 3], [4, 0, 0], [4, 0, 1], [4, 0, 2], [4, 0, 3], [4, 1, 0], [4, 1, 1], [4, 1, 2], [4, 1, 3], [4, 2, 0], [4, 2, 1], [4, 2, 2], [4, 2, 3], [4, 3, 0], [4, 3, 1], [4, 3, 2], [4, 3, 3], [4, 4, 0], [4, 4, 1], [4, 4, 2], [4, 4, 3], [4, 5, 0], [4, 5, 1], [4, 5, 2], [4, 5, 3], [5, 0, 0], [5, 0, 1], [5, 0, 2], [5, 0, 3], [5, 1, 0], [5, 1, 1], [5, 1, 2], [5, 1, 3], [5, 2, 0], [5, 2, 1], [5, 2, 2], [5, 2, 3], [5, 3, 0], [5, 3, 1], [5, 3, 2], [5, 3, 3], [5, 4, 0], [5, 4, 1], [5, 4, 2], [5, 4, 3], [5, 5, 0], [5, 5, 1], [5, 5, 2], [5, 5, 3], [6, 0, 0], [6, 0, 1], [6, 0, 2], [6, 0, 3], [6, 1, 0], [6, 1, 1], [6, 1, 2], [6, 1, 3], [6, 2, 0], [6, 2, 1], [6, 2, 2], [6, 2, 3], [6, 3, 0], [6, 3, 1], [6, 3, 2], [6, 3, 3], [6, 4, 0], [6, 4, 1], [6, 4, 2], [6, 4, 3], [6, 5, 0], [6, 5, 1], [6, 5, 2], [6, 5, 3]]
[[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 0 3]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [1 0 3]
 [2 0 0]
 [2 0 1]
 [2 0 2]
 [2 0 3]
 [3 0 0]
 [3 0 1]
 [3 0 2]
 [3 0 3]
 [4 0 0]
 [4 0 1]
 [4 0 2]
 [4 0 3]
 [5 0 0]
 [5 0 1]
 [5 0 2]
 [5 0 3]
 [6 0 0]
 [6 0 1]
 [6 0 2]
 [6 0 3]
 [0 1 0]
 [0 1 1]
 [0 1 2]
 [0 1 3]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 1 3]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 1 3]
 [3 1 0]
 [3 1 1]
 [3 1 2]
 [3 1 3]
 [4 1 0]
 [4 1 1]
 [4 1 2]
 [4 1 3]
 [5 1 0]
 [5 1 1]
 [5 1 2]
 [5 1 3]
 [6 1 0]
 [6 1 1]
 [6 1 2]
 [6 1 3]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [0 2 3]
 [1 2 0]
 [1 2 1]
 [1 2 2]
 [1 2 3]
 [2 2 0]
 [2 2 1]
 [2 2 2]
 [2 2 3]
 [3 2 0]
 [3 2 1]
 [3 2 2]
 [3 2 3]
 [4 2 0]
 [4 2 1]
 [4 2 2]
 [4 2 3]
 [5 2 0]
 [5 2 1]
 [5 2 2]
 [5 2 3]
 [6 2 0]
 [6 2 1]
 [6 2 2]
 [6 2 3]
 [0 3 0]
 [0 3 1]
 [0 3 2]
 [0 3 3]
 [1 3 0]
 [1 3 1]
 [1 3 2]
 [1 3 3]
 [2 3 0]
 [2 3 1]
 [2 3 2]
 [2 3 3]
 [3 3 0]
 [3 3 1]
 [3 3 2]
 [3 3 3]
 [4 3 0]
 [4 3 1]
 [4 3 2]
 [4 3 3]
 [5 3 0]
 [5 3 1]
 [5 3 2]
 [5 3 3]
 [6 3 0]
 [6 3 1]
 [6 3 2]
 [6 3 3]
 [0 4 0]
 [0 4 1]
 [0 4 2]
 [0 4 3]
 [1 4 0]
 [1 4 1]
 [1 4 2]
 [1 4 3]
 [2 4 0]
 [2 4 1]
 [2 4 2]
 [2 4 3]
 [3 4 0]
 [3 4 1]
 [3 4 2]
 [3 4 3]
 [4 4 0]
 [4 4 1]
 [4 4 2]
 [4 4 3]
 [5 4 0]
 [5 4 1]
 [5 4 2]
 [5 4 3]
 [6 4 0]
 [6 4 1]
 [6 4 2]
 [6 4 3]
 [0 5 0]
 [0 5 1]
 [0 5 2]
 [0 5 3]
 [1 5 0]
 [1 5 1]
 [1 5 2]
 [1 5 3]
 [2 5 0]
 [2 5 1]
 [2 5 2]
 [2 5 3]
 [3 5 0]
 [3 5 1]
 [3 5 2]
 [3 5 3]
 [4 5 0]
 [4 5 1]
 [4 5 2]
 [4 5 3]
 [5 5 0]
 [5 5 1]
 [5 5 2]
 [5 5 3]
 [6 5 0]
 [6 5 1]
 [6 5 2]
 [6 5 3]]
```

It may not show because the indices are used self-consistently within the tests, but I'm in favor of keeping the original index order.

**Comment by c-prather** [comment]
Good point, and an easy enough change.  I've switched the index order to match the old behavior.

Idle question: would it be useful to split out the python package, now that we have an org and can keep it nearby?  I'd love to use it as a submodule in my own python library, but it needs some love and a faster development cadence if it's going to be useful to people as more than an example.  Not to mention maybe some of its own tests....

**Comment by Yurlungur** [comment]
> Idle question: would it be useful to split out the python package, now that we have an org and can keep it nearby? I'd love to use it as a submodule in my own python library, but it needs some love and a faster development cadence if it's going to be useful to people as more than an example. Not to mention maybe some of its own tests....

That might be worth bringing up at a parthenon call.

**Comment by c-prather** [comment]
Noted, I'll do that next week.  I'm actually happy to take the lead on a split-out parthenon_tools.  If I'm allowed to set the style a bit it would end up looking something like [pyharm](https://github.com/AFD-Illinois/pyharm), so maybe folks can evaluate a potential change in that light.

**Comment by Yurlungur** [comment]
@bprather @pgrete what's the status of this PR?

**Review by pgrete — APPROVED** [review]

**Pull request merged**
