### PR TITLE
Use `GNUInstallDirs` to fix installation problems on mac

### PR DESCRIPTION
**Pull request by pbrady**
## PR Summary

A `make install` on my mac generated the following error:
```console
     479    -- Installing: /parthenon/.
  >> 480    CMake Error at src/cmake_install.cmake:57 (file):
     481      file INSTALL cannot make directory "/parthenon/.": No such file or
     482      directory.
     483    Call Stack (most recent call first):
     484      cmake_install.cmake:42 (include)
     485
     486
  >> 487    make: *** [Makefile:103: install] Error 1
```

This PR uses `GNUInstallDirs` to ensure things are defined.  The installed directory structure looks correct but I've never installed it before so...

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Oh! This bit me in a  previous project and I forgot about it. Good catch! I think this is a sufficiently trivial fix we don't need changelog, etc...

P.S., We often work on branches in parthenon, rather than forks. Would you like push access so you can make those?

**Comment by pbrady** [comment]
Thanks!  Push access would be great.

**Comment by Yurlungur** [comment]
Done

**Comment by pbrady** [comment]
Is the CI failure due to the fork workflow or just some random error?

**Comment by Yurlungur** [comment]
Looks to me like the CI machine had some internet connection issue:
```bash
     for file: [/__w/parthenon/parthenon/tst/regression/gold_standard/parthenon_regression_gold_v19.tgz]
      expected hash: [e1d1a06b9cf9b761d42d0b6b241056ac75658db90138b6b867b1ca7ead4308af4f980285af092b40aee1dbbfb68b4e8cb15efcc9b83d7930c18bf992ae95c729]
        actual hash: [cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e]
             status: [52;"Server returned nothing (no headers, no **data)"]**
```
If this persists, you might try moving from a fork to a branch. It's possible the CI machine doesn't like running forks. (I vaguely remember hitting that previously)

**Comment by pgrete** [comment]
The CI error might have been related to a network outage here (in addition to coming from a fork).

I had a look at the code and do not really understand what the issue was and why the proposed changes fix it.
Is there any more documentation (or similar).
I'm mostly worried about potential side effects on various platforms/software environments (that we naturally do not cover with our existing regression tests).

**Comment by pbrady** [comment]
The install part was relying on `CMAKE_INSTALL_...` variables that are not necessarily set by default.  Adding the `include(GNUInstallDirs)` sets all the `CMAKE_INSTALL_...` variables to the "standard" definitions.  I disabled the auto-merge that @Yurlungur had set due to my not understanding how the headers were consumed by other projects (riot) and encountering some errors.   

I'll remove the draft status after I sort things out.

**Comment by pbrady** [comment]
This is ready.  I've tested out the installed parthenon with riot and that works so this is probably doing the right thing.

**Comment by Yurlungur** [comment]
@pgrete @pdmullen @jdolence @BenWibking @lroberts36 @forrestglines can we get one more approval?

**Comment by pdmullen** [comment]
I would be happy to approve this (hence instantiating the auto-merge), but @pgrete  raised some concerns above, so I think it best that he takes a look too.

**Review by pgrete — APPROVED** [review]
Looks good. I just tested that at least locally this works as expected and it does!
I'm approving (tough I think it'd be nice to also add it to the changelog so that people like @anku94 who use it as library know that there was a change related how the install works/behaves).

**Comment by pgrete** [comment]
Looks like I had to re-enable auto-merge to trigger the extended CI tests.

**Comment by pgrete** [comment]
Style check still doesn't seem to trigger for forks. As the extended test pass I'm manually pulling the trigger.

**Pull request merged**
