### PR TITLE
Add library alias for parthenon so that install and subdirectory looks the same for consuming libraries

### PR DESCRIPTION
**Pull request by AndrewGaspar**
## PR Summary

This change simply adds a library alias `Parthenon::parthenon` for `parthenon` so that using Parthenon as a subdirectory vs. as an install is consistent

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md

### CODE REVIEW

**Comment by brryan** [comment]
@AndrewGaspar Looks good to me! I like the documentation.

**Review by brryan — APPROVED** [review]

**Review by JoshuaSBrown — APPROVED** [review]

**Comment by JoshuaSBrown** [comment]
This has already been merged into https://github.com/lanl/parthenon/pull/284

**Comment by AndrewGaspar** [comment]
Reopening this since #284 is blocked for now.

**Comment by JoshuaSBrown** [comment]
Good idea.

**Review by pgrete — APPROVED** [review]

**Pull request merged**
