### PR TITLE
add macOS CI

### PR DESCRIPTION
**Pull request by BenWibking**
Adds macOS CI on GitHub actions.

## PR Summary

This helps ensure Parthenon runs smoothly on macOS.

This PR may not complete successfully when it's first run (most likely due to missing dependencies), since GitHub provides no way to test actions before running them in production. If this happens, I will create a new PR to fix any issues that arise.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Great to have this included in the CI. @pdmullen maybe you should also take a look as you're our other resident OSX user

**Comment by pdmullen** [comment]
LGTM! Looks like it is testing again MacOS Sonoma; if we want to keep testing the latest OS, then we may periodically have to bump.

**Comment by BenWibking** [comment]
> LGTM! Looks like it is testing again MacOS Sonoma; if we want to keep testing the latest OS, then we may periodically have to bump.

Good catch, thanks! I've changed it to use the `macos-latest` image, which should as of today, run on macOS Sonoma on Apple Silicon (https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/).

**Comment by BenWibking** [comment]
It looks like GitHub doesn't run new CI actions in PRs, so there's a good chance this will fail in some way when it's run (most likely due to missing dependencies in the macOS image). I will create a PR to fix things if this happens.

**Comment by Yurlungur** [comment]
@pdmullen can you click approve? Actually need 2 approving reviews for a merge to go through.

**Review by pdmullen — APPROVED** [review]

**Comment by BenWibking** [comment]
@Yurlungur Do you know why the auto-merge isn't triggering?

**Comment by pdmullen** [comment]
Sometimes it just needs to be re-triggered... just attempted that

**Pull request merged**
