### PR TITLE
Add some profiling regions to tasks in particles example

### PR DESCRIPTION
**Pull request by maximumcats**
## PR Summary

Profiling regions are added to the particles example for easier visualizations in tools like Nsight Systems.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by Yurlungur** [comment]
Great to have this! Ping some of us when this is ready for review.

**Comment by maximumcats** [comment]
This is good for now; I am sure I will have more coming later but I want to spend a little time understanding the software design a little better before marking up the rest. Also, a way to do this which is a little easier is to create a simple class whose constructor calls pushRegion() and whose destructor calls popRegion(), so you just create a copy of the object at the top of the routine and don't need to remember to destroy it, when it goes out of scope the destructor will trigger the region end, so we can cut down on number of lines of code by half (and write less error-prone code).

**Comment by Yurlungur** [comment]
> Also, a way to do this which is a little easier is to create a simple class whose constructor calls pushRegion() and whose destructor calls popRegion()

Oh that's cool. We should definitely add that.

**Review by Yurlungur — APPROVED** [review]

**Comment by Yurlungur** [comment]
Tagging @brryan and @jdolence for review

**Review by jlippuner — APPROVED** [review]
Looks great! I like the idea of a timer class that pushes and pops on construction/destruction.

**Pull request merged**
