### PR TITLE
Remove DerivedOwnership from docs/interface

### PR DESCRIPTION
**Pull request by INNeira**
Resolving issue #455

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Thanks for doing this.

**Comment by Yurlungur** [comment]
And also welcome to the project. Great to see a new face! :)

**Review by jlippuner — APPROVED** [review]
Awesome! Thanks @INNeira and welcome!

**Comment by jlippuner** [comment]
Unfortunately, our CI currently can't handle PRs from forked repos (see #457). I've pulled your change into the `parthenon` repo and created a new PR: #458

Thanks again for your contribution, @INNeira!

**Comment by INNeira** [comment]
Thanks to you too @jlippuner for be awesome with new users! Really thanks a lot!

**Pull request closed without merging**
