### PR TITLE
Add parallel scan

### PR DESCRIPTION
**Pull request by brryan**
## PR Summary

`Kokkos::parallel_scan` would be really useful for relating swarm indices to zone indices on device in a parallel way. This PR adds `parthenon::par_scan` to the existing `parthenon::par_for` and `parthenon::par_reduce`. 

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
This seems like a reasonable strategy.

**Comment by pgrete** [comment]
Ping me when this is ready for review. I think the overall approach is reasonable (as mentioned on Matrix), but a quick scan of the code showed several places where conditional counting the arguments are still used.

**Comment by brryan** [comment]
Removing the `std::enable_if` calls actually generates compile time errors e.g.
```
In file included from /home/brryan/github/parthenon/tst/unit/kokkos_abstraction.cpp:26:
/home/brryan/github/parthenon/src/kokkos_abstraction.hpp: In instantiation of 'void parthenon::dispatch_impl::kokkos_dispatch(parthenon::dispatch_impl::ParallelForDispatch, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Kokkos::RangePolicy<Kokkos::Experimental::WorkItemProperty::ImplWorkItemProperty<1> >, const int&, int, int, int, test_wrapper_3d(T, parthenon::DevExecSpace) [with T = parthenon::LoopPatternFlatRange; parthenon::DevExecSpace = Kokkos::OpenMP]::<lambda(int, int, int)>}]':
[...]
/home/brryan/github/parthenon/src/kokkos_abstraction.hpp:170:23: error: no matching function for call to 'parallel_for(const std::__cxx11::basic_string<char>&, Kokkos::RangePolicy<Kokkos::Experimental::WorkItemProperty::ImplWorkItemProperty<1> >, const int&, int, int, int, test_wrapper_3d(T, parthenon::DevExecSpace) [with T = parthenon::LoopPatternFlatRange; parthenon::DevExecSpace = Kokkos::OpenMP]::<lambda(int, int, int)>)'
  170 |   Kokkos::parallel_for(std::forward<Args>(args)...);
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
/home/brryan/github/parthenon/external/Kokkos/core/src/Kokkos_Parallel.hpp:157:13: note: candidate: 'template<class ExecPolicy, class FunctorType> void Kokkos::parallel_for(const ExecPolicy&, const FunctorType&, const string&, typename std::enable_if<Kokkos::is_execution_policy<Policy>::value>::type*)'
  157 | inline void parallel_for(
      |             ^~~~~~~~~~~~
/home/brryan/github/parthenon/external/Kokkos/core/src/Kokkos_Parallel.hpp:157:13: note:   template argument deduction/substitution failed:
In file included from /home/brryan/github/parthenon/tst/unit/kokkos_abstraction.cpp:26:
/home/brryan/github/parthenon/src/kokkos_abstraction.hpp:170:23: note:   candidate expects 4 arguments, 7 provided
  170 |   Kokkos::parallel_for(std::forward<Args>(args)...);
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Looks like we still need the `enable_if`s so higher-dimension `par_dispatch` function signatures don't clobber lower-dimension ones with variable `Args`? Anyway I'm leaving the `enable_if`s in here, and this is otherwise good to go I think (I didn't add `par_scan` to the documentation but we don't document `par_for` or `par_reduce` either)

**Comment by brryan** [comment]
> Ping me when this is ready for review. I think the overall approach is reasonable (as mentioned on Matrix), but a quick scan of the code showed several places where conditional counting the arguments are still used.

Oops, sorry, I forgot to ping when this was ready @pgrete (if you are OK with the conditional counting, it seems to still be necessary for multiple dimensionality support).

**Review by pgrete — APPROVED** [review]
LGTM
I think the tag dispatch approach works well.
We might have a bug in the main abstraction where we miss guards already present in the MeshBlock implementation, but I'll check that separately and potentially open another PR.

**Pull request merged**
