### PR TITLE
Remove IAS performance regression test

### PR DESCRIPTION
**Pull request by pgrete**
## PR Summary

GitLab CI infrastructure at IAS seems to be broken.
I'm working on migrating to GitHub Action runners in Hamburg anyway, so I suggest to remove the now defunct performance regression test at IAS so that is doesn't hold up other merges.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]

**Comment by Yurlungur** [comment]
I suggest we also simply not require darwin tests for now until I can get them working again. (Already not required since they have to be triggered manually.)

**Review by forrestglines — APPROVED** [review]

**Comment by forrestglines** [comment]
So with the CI's mostly broken but there's a few PR's ready to review/merge, are we just merging without full CI regression checking?

**Comment by pgrete** [comment]
> So with the CI's mostly broken but there's a few PR's ready to review/merge, are we just merging without full CI regression checking?

Yes (and just to be clear, the things that are currently broken are the performance regression test on both IAS and Darwin).
The short and extended regression test suite and the build tests still run (as they have already been migrated to GitHub).

**Comment by pgrete** [comment]
Also someone needs to force-merge this PR as the GitLab test is currently required, ping @jdolence 

PS-ping: Once the repo is at parthenon-hpc-lab more people will have the power to force-merge ;) @jdolence

**Comment by pgrete** [comment]
I'm force merging now so that the failing test is not preventing other PRs.

**Pull request merged**
