### PR TITLE
Fix length-1 vectors in output format version >= 3

### PR DESCRIPTION
**Pull request by brryan**
## PR Summary

With parthenon output format version 3 introduced in #781, scalars are now output as scalars instead of length 1 vectors, drawing a distinction between scalars and length 1 vectors. Previously, `phdf` would identify length-1 vectors as scalars and reshape such arrays in the `Get` call. This breaks length-1 vectors that we sometimes have downstream; I missed fixing this when working on #781. This small PR fixes this issue.

## PR Checklist

- [x] Code passes cpplint
- [x] New features are documented.
- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [x] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by brryan** [comment]
@par-hermes format

**Comment by brryan** [comment]
This was actually a bug because in output format version 3 `vLen` was being set to `vShape[1]`, which would be either a length of a component index or `Nx3`.  And then if `vLen` was 1 the array would be reshaped. BUT if `vLen = Nx3 = 1`, the array would just be reshaped to `nblocks, nx3, nx2, nx1` i.e. it would be unchanged. Since this bug would only occur for length-1 vector data, I don't *think* this change should break either athenapk or kharma output

**Comment by brryan** [comment]
@par-hermes format

**Comment by c-prather** [comment]
The changes themselves look fine, though I don't output any length-1 vectors to test.

Is there a reason to use two `reshape()` calls here though, rather than `squeeze()`?

**Comment by brryan** [comment]
> The changes themselves look fine, though I don't output any length-1 vectors to test.
> 
> Is there a reason to use two `reshape()` calls here though, rather than `squeeze()`?

Fortunately `output_hdf5` includes length-1 vectors (hence the need for an upgold). Also, I use length-1 vectors in phoebus and this works there.

The `reshape` code is from at least a while ago; in the interest of time I'd rather just leave it as is since I don't think there are performance or correctness issues with `reshape` vs `squeeze`.

**Review by c-prather — APPROVED** [review]

**Comment by c-prather** [comment]
Fair enough. When someone gets around to it, `squeeze` will definitely use less memory and likely be faster -- maybe something for a Python cleanup PR later on.

**Review by Yurlungur — APPROVED** [review]
Seems fine to me but an AthenaPK developer should look at it

**Comment by pgrete** [comment]
The pipeline failed: https://github.com/parthenon-hpc-lab/parthenon/actions/runs/3938681656/jobs/6737654886

@brryan looks like not all gold standard content is up to date

**Comment by brryan** [comment]
@pgrete OK this should be working now, didn't require an upgold (only `phdf.py` changes anyway)

**Pull request merged**
