### PR TITLE
[Trivial] Make more `EvolutionDriver` functions overridable

### PR DESCRIPTION
**Pull request by c-prather**
Anything I write here will be longer than the change itself.

Motivation is KHARMA sometimes needs to choose the timestep in unique ways. This has previously been done in the per-package `EstimateTimestep` by manipulating the block/package's return, but globally-enforced limits or alternatives would be cleaner.

Also included a mark for `OutputCycleDiagnostics`, in case having `t` and `dt` to 16 digits of precision isn't somebody's jam for some inscrutable reason.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [ ] Changes are summarized in CHANGELOG.md
- [ ] Change is breaking (API, behavior, ...)
  - [ ] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [ ] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]

**Comment by Yurlungur** [comment]
One more approval required

**Review by pdmullen — APPROVED** [review]

**Comment by Yurlungur** [comment]
FYI some tests failing @bprather

**Comment by pgrete** [comment]
hmm, did this auto-merge with test failing?

**Comment by pgrete** [comment]
And with respect to the PR, I might have suggested to mention that this is possible now in the docs.

**Pull request merged**
