### PR TITLE
[Breaking change] Remove NaN payload tags infrastructure

### PR DESCRIPTION
**Pull request by BenWibking**
## PR Summary

This removes the `NaN` payload tags infrastructure.

It is unused, and the unit test causes a runtime error with UndefinedBehaviorSanitizer. See https://github.com/parthenon-hpc-lab/parthenon/issues/1107.

## PR Checklist

- [ ] Code passes cpplint
- [ ] New features are documented.
- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Code is formatted
- [x] Changes are summarized in CHANGELOG.md
- [x] Change is breaking (API, behavior, ...)
  - [x] Change is *additionally* added to CHANGELOG.md in the breaking section
  - [x] PR is marked as breaking
  - [ ] Short summary API changes at the top of the PR (plus optionally with an automated update/fix script)
- [ ] CI has been triggered on [Darwin](https://re-git.lanl.gov/eap-oss/parthenon/-/pipelines) for performance regression tests.
- [ ] Docs build
- [ ] (@lanl.gov employees) Update copyright on changed files

### CODE REVIEW

**Comment by BenWibking** [comment]
Well, replacing `1 / 0.0` with either `std::numeric_limits<real_t>::signaling_NaN()` or `NAN` (should be a quiet NaN) causes the test to fail... 🧐

**Comment by lroberts36** [comment]
This feature has not ended up being used at all, so one solution would be to remove the test and `utils/nan_payload_tag.hpp`

**Comment by pgrete** [comment]
Do we envision any use in the (near) future? If not, then I'm in favor of removing unused code.

**Review by lroberts36 — APPROVED** [review]
Yeah, I had some ideas for how to use this with sparse but I don't think there is any likely use in the near future.

**Review by Yurlungur — APPROVED** [review]
I'm also fine with removing this.

**Pull request merged**
